site_name: PMP
theme:
  name: material
  features:
    - navigation.instant
    - content.action.edit
  logo: Styling/logo.svg
  favicon: Styling/favicon.png
docs_dir: Documentatie
exclude_docs: |
  /Archive/
  /Notes/
  /UML/

extra_css:
- Styling/stylesheet.css

plugins:
    - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        num_workers: 8
    - search
    - mkdocs-nav-weight
    - include-markdown

repo_url: https://github.com/DCReceveur/pre-afstudeer-docs
edit_uri: tree/main/Documentatie
